CREATE TABLE Customer (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FirstName] VARCHAR(60) NOT NULL,
	[LastName] VARCHAR(60) NOT NULL,
	[Email] VARCHAR(160) NOT NULL,
	[Password] CHAR(32) NOT NULL
)

CREATE TABLE Product (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Title] VARCHAR(80) NOT NULL,
	[Description] VARCHAR(1024) NOT NULL,
	[Slug] VARCHAR(160) NOT NULL,
	[Price] MONEY NOT NULL,
	[Image] VARCHAR(1024) NOT NULL
)